### PR TITLE
Mb add cust prod c

### PR DESCRIPTION
**Pull request by melissabell456**
# Description
This PR covers:
-Product Types: tests and model for retrieving all product types
-Prompt for user to add new product (posting to db)

## Related Ticket(s)
#4 

## Problem to Solve
When a user wants to add a product, they are required to fill in the fields to post to db

## Proposed Changes
We should to discuss our tests more thoroughly soon. The specific restraints on exact values are beginning to be cumbersome with each PR as our data evolves. I do not think it should be one person's task with every PR to adjust the specific tests to make sure they are flexible enough to pass.

## Expected Behavior
A user can post a new product to sell to the db

## Steps to Test Solution

1. rebuild DB
2. run ```npm start```
3. select option 2 to select an active customer
4. select option 4 to add new product
5. enter appropriate responses to prompt
6. check db to ensure this was added

## Testing

- [x] There are new unit tests in this PR, and I verify that there is full coverage of all new code.
- [x] I certify that all existing tests pass (ALSO SEE NOTES IN PROPOSED CHANGES)

## Documentation
- [ ] There is new documentation in this pull request that must be reviewed..
- [ ] I added documentation for any new classes/methods

### CODE REVIEW

**Comment by kenziebottoms** [comment]
So your tests broke my `getAllStockedProducts() should have a length of 43` test because you're addding to that table. I'd suggest just checking that `getAllStockedProducts()` returns fewer products than `getAllProducts()`

**Review by kenziebottoms — CHANGES_REQUESTED** [review]
So your tests broke my `getAllStockedProducts() should have a length of 43` test because you're addding to that table. I'd suggest just checking that `getAllStockedProducts()` returns fewer products than `getAllProducts()`

**Comment by DavidLarsKetch** [comment]
:point_up: or throw in a `beforeEach` hook. Idk which is faster for you

**Comment by DavidLarsKetch** [comment]
Cleaned up `productsM.test.js` a bit as well.

**Review by kenziebottoms — CHANGES_REQUESTED** [review]
Specify expected format of price and change error message accordingly.

**Review by kenziebottoms — APPROVED** [review]

**Review by jordan-castelloe — APPROVED** [review]

**Pull request merged**
